/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.hasithaa.ballerina.scheduler;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import io.ballerina.runtime.api.Environment;
import io.ballerina.runtime.api.TypeTags;
import io.ballerina.runtime.api.async.Callback;
import io.ballerina.runtime.api.async.StrandMetadata;
import io.ballerina.runtime.api.types.MethodType;
import io.ballerina.runtime.api.types.Type;
import io.ballerina.runtime.api.utils.StringUtils;
import io.ballerina.runtime.api.values.*;
import io.ballerina.runtime.internal.BalStringUtils;

public class Library {

    public static Object readBytes(Environment env, BArray bytes, BTypedesc t) throws IOException {

        // TODO: Check bytes is a byte array, before following line.
        MockInputStream inputStream = new MockInputStream(bytes.getBytes());
        Parser parser = new Parser(inputStream);
        parser.parse();
        if (t.getDescribingType().getTag() == TypeTags.STRING_TAG) {
            return StringUtils.fromString(parser.getResultString());
        } else {
            return parser.getResultInt();
        }
    }

}
