/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.hasithaa.ballerina.scheduler;

import org.testng.annotations.*;

import io.github.hasithaa.ballerina.scheduler.Library;

import static org.testng.Assert.*;

public class LibraryTest {
}
